// /*
//  * MIT License
//  * Copyright (c) 2025 Alexander Gall
//  */

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UnityEngine;

namespace AugmeNDT{
    using Microsoft.MixedReality.Toolkit.Utilities;

    /// <summary>
    /// Class handles the loaded datasets and their respective renderings and data visualizations
    /// </summary>
    public class SceneObjectHandler : MonoBehaviour
    {   
        // Used to load data in various file formats
        private FileLoadingManager fileLoadingManager;
        [SerializeField] private AttributePopulator attributePopulator;//ANU

        // Parent Container which stores all DataVisGroups in the scene
        [SerializeField]
        private GameObject sceneObjectsContainer;
        //GridObjectCollection used to arrange all DataVisGroups in the scene
        private GridObjectCollection gridColl;

        // Stores all loaded data & its derived representations
        [SerializeField]
        private List<DataVisGroup> dataVisGroups;
        Color[] colorScheme;
        // Combines stored groups for combined representations
        [SerializeField]
        private Dictionary<int, DataVisGroup> multiGroups;

        // When introducing multiple DataVisGroups rearrange first the singular Objects in each group
        private bool rearrangeObjects = true;

        // Called only once during the lifetime of the script instance (loading of a scene)
        void Awake()
        {
            // Initialize all members
            fileLoadingManager = new FileLoadingManager();
            dataVisGroups = new List<DataVisGroup>();
            multiGroups = new Dictionary<int, DataVisGroup>();

            sceneObjectsContainer = new GameObject("Scene Objects");
        }

        void Update()
        {

            //Move to individual vis Object(monobehaviour ?)
            if (dataVisGroups.Count > 0)
            {
                foreach (DataVisGroup group in dataVisGroups)
                {
                    group.AlignGridPositions();
                }
            }

        }
        public List<string> GetAttributeNamesOfLastLoadedCsv()
        {
            if (fileLoadingManager == null)
            {
                Debug.LogError("FileLoadingManager not assigned or initialized!");
                return null;
            }

            CsvLoader csvLoader = fileLoadingManager.GetCsvLoader();
            if (csvLoader != null)
            {
               return csvLoader.GetAllAttributeNames();
            }

            return null; // Not a CSV dataset loaded
        }
        /// <summary>
        /// Returns the amount of loaded dataVisGroups
        /// </summary>
        /// <returns></returns>
        public int GetAmountOfDataVisGroups()
        {
            return dataVisGroups.Count;
        }

        /// <summary>
        /// Loads a file based on the picked file path and renders all possible representations
        /// </summary>
        /// <returns></returns>
        public async Task<string> LoadObject()
        {
            // Start async Loadings
            string filePath = await fileLoadingManager.StartPicker();

            // If file loading failed
            if (filePath == "")
            {
                return null;
            }

            bool loadingSucceded = await fileLoadingManager.LoadDataset();

            //## Wait for Loadings to finish ##
            if (!loadingSucceded)
            {
                Debug.LogError("Loading aborted!");
                return null;
            }

            Debug.Log("> Adding DataVis Group");

            // Add Group
            dataVisGroups.Add(fileLoadingManager.GetDataVisGroup());
            int lastIndex = dataVisGroups.Count - 1;

            // Render all representations (whose data is available)
            dataVisGroups[lastIndex].RenderAll(VisType.MDDGlyphs);


            dataVisGroups[lastIndex].ArrangeObjectsSpatially();

            // Add Group to sceneObjectsContainer container
            dataVisGroups[lastIndex].GetGroupContainer().transform.parent = sceneObjectsContainer.transform;
            ArrangeGroupsSpatially();

            return filePath;
        }

        /// <summary>
        /// Loads a file based on a predefined path and renders all possible representations
        /// </summary>
        /// <returns></returns>
        /// //ANU
        public async Task<DataVisGroup> LoadPreSelectedObject(string filePath)
        {
            fileLoadingManager.SetFilePath(filePath);
            bool loadingSucceded = await fileLoadingManager.LoadDataset();

            //## Wait for Loadings to finish ##
            if (!loadingSucceded)
            {
                Debug.LogError("Loading aborted!");
                return null;
            }
           

            Debug.Log("> Adding DataVis Group");
           
            // Add Group
            dataVisGroups.Add(fileLoadingManager.GetDataVisGroup());
            int lastIndex = dataVisGroups.Count - 1;

            // Render all representations (whose data is available)
            dataVisGroups[lastIndex].RenderAll(VisType.MDDGlyphs);


            dataVisGroups[lastIndex].ArrangeObjectsSpatially();

            // Add Group to sceneObjectsContainer container
            dataVisGroups[lastIndex].GetGroupContainer().transform.parent = sceneObjectsContainer.transform;
            ArrangeGroupsSpatially();
            //anu
            //CsvLoader loader = fileLoadingManager.GetCsvLoader();
            //if (loader != null && attributePopulator != null)
            //{
            //    attributePopulator.Initialize(loader);
            //}

            return dataVisGroups[lastIndex];
        }
      
         public async Task<DataVisGroup> LoadPreview(string filePath)
         {
                fileLoadingManager.SetFilePath(filePath);
                bool loadingSucceded = await fileLoadingManager.LoadDataset();

                if (!loadingSucceded)
                {
                    Debug.LogError("Preview loading aborted!");
                    return null;
                }

                // Add Group
                DataVisGroup newGroup = fileLoadingManager.GetDataVisGroup();
                dataVisGroups.Add(newGroup);

                // Render only the fibers for preview
                newGroup.RenderFibersforPreview(VisType.MDDGlyphs);

                // Deactivate the preview object so it’s hidden at runtime
                if (newGroup.GetGroupContainer() != null)
                    newGroup.GetGroupContainer().SetActive(true);

                return newGroup;
         }

        
        /// <summary>
        /// Method iterates through all selected groups and adds them to the multiGroups dictionary (if found in the dataVisGroups list).
        /// </summary>
        /// <param name="selectedGroups"></param>
        public void CreateMultiGroup(List<int> selectedGroups)
        {
            foreach (var selection in selectedGroups)
            {
                DataVisGroup temp = dataVisGroups.FirstOrDefault(groupID => groupID.GetGroupID() == selection);

                if (temp != null) multiGroups.Add(selection, temp);
            }
        }

        /// <summary>
        /// Arranges all groups in a [2 by n] grid and moves it to the best initial start position
        /// </summary>
        public void ArrangeGroupsSpatially()
        {

            if (rearrangeObjects)
            {
                // First arrange all individual groups again
                foreach (var group in dataVisGroups)
                {
                    group.ArrangeObjectsSpatially();
                }
            }
            
            if (gridColl == null)
            {
                gridColl = sceneObjectsContainer.AddComponent<GridObjectCollection>();
                //gridColl.SurfaceType = ObjectOrientationSurfaceType.Cylinder;
                gridColl.CellWidth = 0.60f; //Todo: Use twice the biggest size of the individual grids in the groups
                gridColl.CellHeight = 0.3f; //Todo: Use twice the biggest size of the individual grids in the groups
                gridColl.SortType = CollationOrder.ChildOrder;
                gridColl.Layout = LayoutOrder.ColumnThenRow;
                gridColl.Columns = 2;
                gridColl.Anchor = LayoutAnchor.BottomLeft;
                gridColl.AnchorAlongAxis = true;
            }

            gridColl.UpdateCollection();
            
            GlobalScaleAndPos.SetToBestInitialStartPos(sceneObjectsContainer.transform);
        }

        //#####################     VOLUME METHODS      #####################

        public void ChangeVolumeShader(int selectedGroup, Shader shader)
        {
            //TODO: Change int selectedVolume to reference of Object during interaction
            dataVisGroups[selectedGroup].ChangeVolumeShader(shader);
        }

        //#####################     POLY MODEL METHODS  #####################

        public void HighlightPolyFibers(int selectedGroup, List<int> fiberIDs, Color selectedColor)
        {
            dataVisGroups[selectedGroup].HighlightPolyFibers(fiberIDs, selectedColor);
        }

        //#####################     VIS CHART METHODS   #####################

        /// <summary>
        /// Returns the amount of attributes the abstract dataset has
        /// </summary>
        /// <param name="selectedGroup"></param>
        /// <returns></returns>
        public int GetAttributeCount(int selectedGroup)
        {
            return dataVisGroups[selectedGroup].GetAttributeCount();
        }

        public AbstractDataset GetAbstractDataset(int selectedGroup)
        {
            return dataVisGroups[selectedGroup].GetAbstractDataset();
        }

        /// <summary>
        /// Adds a new abstract visualization object to the selected group and renders it
        /// </summary>
        /// <param name="selectedGroup"></param>
        /// <param name="visType"></param>
        public void AddAbstractVisObject(int selectedGroup, VisType visType)
        {
            dataVisGroups[selectedGroup].RenderAbstractVisObject(visType);
            //Arrange Vis objects
            dataVisGroups[selectedGroup].ArrangeObjectsSpatially();
        }

        /// <summary>
        /// Adds a new abstract visualization object to the selected group and renders it
        /// </summary>
        /// <param name="selectedGroup"></param>
        /// <param name="visType"></param>
        public void AddAbstractVisObject(int selectedGroup, VisType visType, Dictionary<VisChannel, Attribute> setChannels)
        {
            dataVisGroups[selectedGroup].RenderAbstractVisObject(visType, setChannels);
            //Arrange Vis objects
            dataVisGroups[selectedGroup].ArrangeObjectsSpatially();
        }

        /// <summary>
        /// Renders a 4D abstract visualization object combining all csv files found in the groups
        /// </summary>
        public void RenderAbstractVisObjectForMultiGroup()
        {
            Debug.Log("Render Abstract Vis Object of MultiGroup");

            Vis vis = new VisMDDGlyphs();

            foreach (var group in multiGroups)
            {
                //vis.AppendData(group.Value.GetPolyData().ExportForDataVis());
                vis.AppendData(group.Value.GetAbstractCsvData());
            }

            vis.multiGroups = multiGroups;
            GameObject parentContainer = new GameObject("MultiGroupVis");
            vis.CreateVis(parentContainer);

            GlobalScaleAndPos.SetToBestInitialStartPos(parentContainer.transform);
            parentContainer.transform.localPosition = new Vector3(parentContainer.transform.localPosition.x,
                parentContainer.transform.localPosition.y, 0f);
        }

        public void ChangeAxis(int selectedGroup, int selectedVis, int axisID, int selectedDimension, int numberOfTicks)
        {
            //TODO: Change int selectedVis to reference of Object during interaction
            dataVisGroups[selectedGroup].ChangeAxis(selectedVis, axisID, selectedDimension, numberOfTicks);
        }

        //ANU
        

    }

}
